name: Download IPA by Version

on:
  workflow_dispatch:
    inputs:
      APP_ID:
        description: 'App Store App ID (e.g., 6449977582)'
        required: true
      APP_VERSION_ID:
        description: 'App Version ID you want to download (e.g., 123456789)'
        required: true
      APPLE_ID:
        description: 'Your Apple ID'
        required: true
      APPLE_PASSWORD:
        description: 'Your Apple ID password (No 2FA)'
        required: true
      APP_COUNTRY:
        description: 'App Store Country Code (e.g., TW)'
        required: false
        default: 'TW'

jobs:
  download-ipa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r ipatool-py/requirements.txt

      - name: Download IPA
        run: |
          mkdir ipaDown
          python3 ipatool-py/main.py download_id \
            --appId "${{ github.event.inputs.APP_ID }}" \
            --appVer "${{ github.event.inputs.APP_VERSION_ID }}" \
            --appleid "${{ github.event.inputs.APPLE_ID }}" \
            --password "${{ github.event.inputs.APPLE_PASSWORD }}" \
            --country "${{ github.event.inputs.APP_COUNTRY }}" \
            --output ipaDown

      - name: Zip IPA
        run: |
          zip -r ipa-output.zip ipaDown

      - name: Push IPA to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          mkdir -p output
          mv ipa-output.zip output/
          git fetch origin
          git checkout main
          git pull
          git add output/ipa-output.zip
          git commit -m "Add IPA zip for ${{ github.event.inputs.APP_ID }} version_id ${{ github.event.inputs.APP_VERSION_ID }}"
          git push origin main
